#!/usr/bin/env node

/**
 * Development script for QR Code Generator Pro Chrome Extension
 * Sets up development environment and file watching
 */

const fs = require('fs');
const path = require('path');

console.log('🚀 Starting QR Code Generator Pro in development mode...');

// Check if source files exist
const srcDir = path.join(__dirname, '..', 'src');
const manifestPath = path.join(__dirname, '..', 'manifest.json');

if (!fs.existsSync(srcDir)) {
  console.error('❌ Source directory not found:', srcDir);
  process.exit(1);
}

if (!fs.existsSync(manifestPath)) {
  console.error('❌ Manifest file not found:', manifestPath);
  process.exit(1);
}

console.log('✅ Development environment ready!');
console.log('');
console.log('📂 Project structure:');
console.log('├── src/');
console.log('│   ├── popup/');
console.log('│   │   ├── popup.html');
console.log('│   │   └── popup.js');
console.log('│   ├── assets/');
console.log('│   │   └── icons/');
console.log('│   └── lib/');
console.log('│       └── qrcode.min.js');
console.log('├── manifest.json');
console.log('└── dist/ (generated by build)');
console.log('');
console.log('🔧 Development commands:');
console.log('• npm run build  - Build extension for production');
console.log('• npm run clean  - Clean build artifacts');
console.log('• npm run zip    - Create distribution package');
console.log('• npm run test   - Run tests');
console.log('');
console.log('📝 To load extension in Chrome:');
console.log('1. Run "npm run build" to create dist/ folder');
console.log('2. Open Chrome → chrome://extensions/');
console.log('3. Enable "Developer mode"');
console.log('4. Click "Load unpacked" and select dist/ folder');
console.log('');
console.log('💡 Tip: Rebuild after making changes to see updates in Chrome');

// Basic file validation
try {
  const popupHtml = path.join(srcDir, 'popup', 'popup.html');
  const popupJs = path.join(srcDir, 'popup', 'popup.js');
  const qrLib = path.join(srcDir, 'lib', 'qrcode.min.js');
  
  if (fs.existsSync(popupHtml)) console.log('✅ popup.html found');
  else console.log('⚠️  popup.html missing');
  
  if (fs.existsSync(popupJs)) console.log('✅ popup.js found');
  else console.log('⚠️  popup.js missing');
  
  if (fs.existsSync(qrLib)) console.log('✅ qrcode.min.js found');
  else console.log('⚠️  qrcode.min.js missing');
  
} catch (error) {
  console.error('❌ Error validating files:', error.message);
}